Vince\Bundle\CmsBundle\Entity\ArticleMeta:
    type: mappedSuperclass
    fields:
        contents:
            type: text
        createdAt:
            type: datetime
            column: created_at
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            column: updated_at
            gedmo:
                timestampable:
                    on: update