Vince\Bundle\CmsBundle\Entity\Article:
    type: mappedSuperclass
    repositoryClass: Vince\Bundle\CmsBundle\Entity\Repository\ArticleRepository
    fields:
        title:
            type: string
            length: 255
        slug:
            type: string
            length: 255
            unique: true
            gedmo:
                slug:
                    fields: [title]
        createdAt:
            type: datetime
            column: created_at
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            column: updated_at
            gedmo:
                timestampable:
                    on: update
        summary:
            type: text
        tags:
            type: array
        url:
            type: string
            length: 255
            nullable: true
            unique: true
        startedAt:
            type: date
            nullable: true
            column: started_at
        endedAt:
            type: date
            nullable: true
            column: ended_at
    manyToOne:
        template:
            targetEntity: Vince\Bundle\CmsBundle\Entity\Template
            joinColumn:
                name: template_id
                referencedColumnName: id
                nullable: false
                onDelete: CASCADE
    indexes:
        search_idx:
            columns: slug
    lifecycleCallbacks:
        prePersist: [initHomepage]