Vince\Bundle\CmsBundle\Entity\Article:
    type: entity
    table: article
    repositoryClass: Vince\Bundle\CmsBundle\Entity\Repository\ArticleRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        title:
            type: string
            length: 255
        slug:
            type: string
            length: 255
            unique: true
            gedmo:
                slug:
                    fields: [title]
        createdAt:
            type: datetime
            column: created_at
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            column: updated_at
            gedmo:
                timestampable:
                    on: update
        summary:
            type: text
        tags:
            type: array
        url:
            type: string
            length: 255
            nullable: true
            unique: true
        startedAt:
            type: date
            nullable: true
            column: started_at
        endedAt:
            type: date
            nullable: true
            column: ended_at
    oneToMany:
        metas:
            targetEntity: Vince\Bundle\CmsBundle\Entity\ArticleMeta
            mappedBy: article
        contents:
            targetEntity: Vince\Bundle\CmsBundle\Entity\Content
            mappedBy: article
        menus:
            targetEntity: Vince\Bundle\CmsBundle\Entity\Menu
            mappedBy: article
    manyToOne:
        template:
            targetEntity: Vince\Bundle\CmsBundle\Entity\Template
            joinColumn:
                name: template_id
                referencedColumnName: id
                nullable: false
    manyToMany:
        categories:
            targetEntity: Vince\Bundle\CmsBundle\Entity\Category
            joinTable:
                name: article_category
                joinColumns:
                    article_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    category_id:
                        referencedColumnName: id
            uniqueConstraints:
                event_user_idx:
                    columns: article_id, category_id
    indexes:
        search_idx:
            columns: slug
    lifecycleCallbacks:
        prePersist: [initHomepage]