Vince\Bundle\CmsBundle\Entity\Block:
    type: mappedSuperclass
    repositoryClass: Vince\Bundle\CmsBundle\Entity\Repository\TranslatableRepository
    gedmo:
        translation:
            locale: locale
    fields:
        name:
            type: string
            length: 255
            unique: true
        title:
            type: string
            length: 255
            gedmo:
                - translatable
        contents:
            type: text
            gedmo:
                - translatable
        startedAt:
            type: date
            nullable: true
            column: started_at
        endedAt:
            type: date
            nullable: true
            column: ended_at
        createdAt:
            type: datetime
            column: created_at
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            column: updated_at
            gedmo:
                timestampable:
                    on: create
