Vince\Bundle\CmsBundle\Entity\Block:
    type: mappedSuperclass
    fields:
        language:
            type: string
            length: 2
        name:
            type: string
            length: 255
            unique: true
        title:
            type: string
            length: 255
        contents:
            type: text
        startedAt:
            type: date
            nullable: true
            column: started_at
        endedAt:
            type: date
            nullable: true
            column: ended_at
        createdAt:
            type: datetime
            column: created_at
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            column: updated_at
            gedmo:
                timestampable:
                    on: create
    indexes:
        search_idx:
            columns: name
    lifecycleCallbacks:
        prePersist: [initOriginal]
