Vince\Bundle\CmsBundle\Entity\Content:
    type: entity
    table: content
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        contents:
            type: text
        createdAt:
            type: datetime
            column: created_at
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            column: updated_at
            gedmo:
                timestampable:
                    on: update
    manyToOne:
        article:
            targetEntity: Vince\Bundle\CmsBundle\Entity\Article
            inversedBy: contents
            joinColumn:
                name: article_id
                referencedColumnName: id
        area:
            targetEntity: Vince\Bundle\CmsBundle\Entity\Area
            joinColumn:
                name: area_id
                referencedColumnName: id