Vince\Bundle\CmsBundle\Entity\Menu:
    type: mappedSuperclass
    repositoryClass: Vince\Bundle\CmsBundle\Entity\Repository\MenuRepository
    gedmo:
        tree:
            type: nested
        translation:
            locale: locale
    fields:
        title:
            type: string
            length: 255
            gedmo:
                - translatable
        slug:
            type: string
            length: 255
            unique: true
            gedmo:
                slug:
                    fields: [title]
        url:
            type: string
            length: 255
            nullable: true
            gedmo:
                - translatable
        target:
            type: string
            length: 255
        path:
            type: string
            length: 255
            nullable: true
            gedmo:
                - translatable
        image:
            type: boolean
            column: image
        startedAt:
            type: date
            nullable: true
            column: started_at
        endedAt:
            type: date
            nullable: true
            column: ended_at
        lft:
            type: integer
            gedmo:
                - treeLeft
        rgt:
            type: integer
            gedmo:
                - treeRight
        root:
            type: integer
            nullable: true
            gedmo:
                - treeRoot
        lvl:
            type: integer
            gedmo:
                - treeLevel
        createdAt:
            type: datetime
            column: created_at
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            column: updated_at
            gedmo:
                timestampable:
                    on: update
