Vince\Bundle\CmsBundle\Entity\Meta:
    type: entity
    table: meta
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        title:
            type: string
            length: 255
        name:
            type: string
            length: 255
        group:
            type: string
            length: 255
            column: meta_group
            nullable: true