services:
    vince.cms.controller.exception:
        class: Vince\Bundle\CmsBundle\Controller\ExceptionController
        parent: twig.controller.exception
        arguments: [@vince.repository.article, @event_dispatcher]

    vince.cms.form.handler:
        class: Vince\Bundle\CmsBundle\Form\Handler\CmsFormHandler
        calls:
            - [setChain, [@vince.processor.chain]]
            - [setRouter, [@router]]

    vince.cms.loader:
        class: Vince\Bundle\CmsBundle\Component\Routing\Loader
        tags:
            - { name: routing.loader }
        calls:
            - [setArticleRepository, [@vince.repository.article]]

    # Twig
    twig.extension.vince.cms:
        class: Vince\Bundle\CmsBundle\Twig\Extension\CmsExtension
        calls:
            - [setSecurityContext, [@security.context]]
            - [addRepository, ['menu', @vince.repository.menu]]
            - [addRepository, ['block', @vince.repository.block]]
        tags:
            - { name: twig.extension }

    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    # Gedmo listeners
    gedmo.listener.tree:
        class: Gedmo\Tree\TreeListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [setAnnotationReader, [@annotation_reader]]

    gedmo.listener.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [setAnnotationReader, [@annotation_reader]]

    gedmo.listener.sluggable:
        class: Gedmo\Sluggable\SluggableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [setAnnotationReader, [@annotation_reader]]

    # CMS loaders
    vince.cms.search.load.listener:
        class: Vince\Bundle\CmsBundle\Listener\SearchListener
        tags:
            - { name: kernel.event_listener, event: vince.cms.search.load, method: onLoad }
        calls:
            - [setArticleRepository, [@vince.repository.article]]

    # CMS forms
    vince.processor.chain:
        class: Vince\Bundle\CmsBundle\Component\Chain\Chain

    vince.processor:
        class: Vince\Bundle\CmsBundle\Component\Processor\Processor
        abstract: true
        calls:
            - [setFormFactory, [@form.factory]]