Vince\Bundle\CmsBundle\Entity\Area:
    properties:
        title:
            - NotBlank: ~
        name:
            - NotBlank: ~
        type:
            - NotBlank: ~
        template:
            - NotNull: ~